# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5e1fbffd9eaa5e9a0a744340df33b78d9f16af64f7867dbe5329fb6ad2aed5dc156afcace452dc0b2e9a7372ddac4f05cfa5992218ca9fee13ed71757a1058b6

test:
  secret_key_base: 0ffe0980ddbf51e37c1b756282a3e5256aa143a14f5c8fd99c36ee1461dcd594d74a7d98e7827dd14bf387ec3594ecd7c727f4f181aa1bca90a0d70465f0c70c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
